-- Generated by scripts/gen-schema.sh — DO NOT EDIT BY HAND.
-- Source of truth: db/ (Dolt). Regenerate with `make schema`.

-- Deduplication of GitHub webhook deliveries by X-GitHub-Delivery id.
CREATE TABLE IF NOT EXISTS deliveries (
    id                    TEXT NOT NULL,
    "event"               TEXT NOT NULL,
    received_at           BIGINT NOT NULL,
    PRIMARY KEY (id)
);

-- A Round is the lifecycle of a single PR head SHA (owner/repo#number @ sha).
-- A new head SHA is a new Round; see ADR-0004.
CREATE TABLE IF NOT EXISTS rounds (
    "owner"               TEXT NOT NULL,
    repo                  TEXT NOT NULL,
    number                INTEGER NOT NULL,
    sha                   TEXT NOT NULL,
    updated_at            BIGINT NOT NULL,
    PRIMARY KEY ("owner", repo, number, sha)
);

-- Latest-state pending store: at most one row per PR per signal-type, the
-- newest summary wins (ADR-0006). Nothing here is garbage-collected; a newer
-- same-type event overwrites the row.
CREATE TABLE IF NOT EXISTS pending (
    "owner"               TEXT NOT NULL,
    repo                  TEXT NOT NULL,
    number                INTEGER NOT NULL,
    signal_type           TEXT NOT NULL,
    sha                   TEXT NOT NULL,
    pr_state              TEXT NOT NULL,
    "summary"             TEXT NOT NULL,
    updated_at            BIGINT NOT NULL,
    PRIMARY KEY ("owner", repo, number, signal_type)
);

-- Raw signals observed for a Round, compiled into a summary at settle time.
-- Keyed by their natural identity so a re-delivered signal replaces, not dupes.
CREATE TABLE IF NOT EXISTS signals (
    "owner"               TEXT NOT NULL,
    repo                  TEXT NOT NULL,
    number                INTEGER NOT NULL,
    sha                   TEXT NOT NULL,
    signal_type           TEXT NOT NULL,   -- checks | comments | mergeability
    source                TEXT NOT NULL,   -- dynamic attribution, e.g. CI / CodeRabbit
    external_id           TEXT NOT NULL,   -- per-source id for replace/dedupe
    severity              TEXT NOT NULL DEFAULT '',
    body                  TEXT NOT NULL DEFAULT '',
    updated_at            BIGINT NOT NULL,
    PRIMARY KEY ("owner", repo, number, sha, signal_type, source, external_id)
);

-- Hub-minted installation tokens for SSE / get_pending auth (ADR-0003).
-- Only the hash is stored; the raw token is shown once at mint time.
-- Auth v2 adds user-binding columns (id ULID, github_user_id, device_label,
-- expires_at, last_used_at, revoked_at); legacy rows keep github_user_id NULL
-- and device_label='legacy'.
CREATE TABLE IF NOT EXISTS tokens (
    token_hash            TEXT NOT NULL,   -- hex sha256 of the raw token
    installation_id       TEXT NOT NULL,
    org                   TEXT NOT NULL DEFAULT '',
    created_at            BIGINT NOT NULL,
    id                    TEXT NOT NULL DEFAULT '',   -- ULID; backfill in code path (legacy rows → 'legacy-<rowid>')
    github_user_id        BIGINT,   -- nullable until v0.4.0
    github_user_login     TEXT,
    device_label          TEXT NOT NULL DEFAULT 'legacy',
    expires_at            BIGINT,   -- NULL = no expiry (legacy)
    last_used_at          BIGINT,
    revoked_at            BIGINT,
    PRIMARY KEY (token_hash)
);

CREATE INDEX IF NOT EXISTS tokens_expires_active ON tokens (revoked_at, expires_at);
CREATE INDEX IF NOT EXISTS tokens_installation ON tokens (installation_id);
CREATE INDEX IF NOT EXISTS tokens_user ON tokens (github_user_id);

-- GitHub App installations. One row per installation_id.
-- app_slug carries the App's URL slug (Auth v2) for /apps/<slug>/installations/new.
CREATE TABLE IF NOT EXISTS installations (
    installation_id       TEXT NOT NULL,
    account_login         TEXT NOT NULL,
    created_at            BIGINT NOT NULL,
    app_slug              TEXT NOT NULL DEFAULT '',   -- GitHub App slug, e.g. "caw-ravencloak" (Auth v2)
    PRIMARY KEY (installation_id)
);

-- Repos associated with each installation.
CREATE TABLE IF NOT EXISTS installation_repos (
    installation_id       TEXT NOT NULL,
    full_name             TEXT NOT NULL,   -- "owner/repo"
    PRIMARY KEY (installation_id, full_name)
);

-- Rebase leases: at most one holder per PR at any time (ADR-0005).
-- UNIQUE(org, repo, pr_number) enforces the single-owner invariant.
-- All timestamps are Unix epoch seconds (INTEGER) to stay portable to Postgres.
CREATE TABLE IF NOT EXISTS leases (
    org                   TEXT NOT NULL,
    repo                  TEXT NOT NULL,
    pr_number             INTEGER NOT NULL,
    holder                TEXT NOT NULL,   -- installation_id of current holder
    expires_at            BIGINT NOT NULL,   -- Unix epoch; grant duration set by Hub
    last_heartbeat_at     BIGINT NOT NULL,   -- updated by holder; orphan detection uses this
    acquired_at           BIGINT NOT NULL,
    CONSTRAINT uq_lease UNIQUE (org, repo, pr_number)
);

CREATE INDEX IF NOT EXISTS leases_expires ON leases (expires_at);

-- GitHub App credentials persisted after the manifest conversion flow.
-- Only one row ever exists (single-app deployment); enforced by CHECK (id = 1).
CREATE TABLE IF NOT EXISTS app_credentials (
    id                    INTEGER NOT NULL,
    app_id                TEXT NOT NULL,
    client_id             TEXT NOT NULL,
    client_secret         TEXT NOT NULL,
    webhook_secret        TEXT NOT NULL,
    pem                   TEXT NOT NULL,
    created_at            BIGINT NOT NULL,
    PRIMARY KEY (id),
    CHECK (id = 1)
);

-- OAuth login sessions for MCP-initiated `login` handoffs (Auth v2).
-- Short-lived (10 min). PKCE-bound; mode is 'loopback' or 'device'.
-- A purger sweeps expired rows every 15 min.
CREATE TABLE IF NOT EXISTS auth_sessions (
    id                    TEXT NOT NULL,   -- ULID
    mode                  TEXT NOT NULL,   -- "loopback" | "device"
    code_challenge        TEXT NOT NULL,   -- S256 hash, base64url
    code_challenge_method TEXT NOT NULL,   -- "S256"
    loopback_redirect     TEXT,
    device_code           TEXT,
    user_code             TEXT,
    client_label          TEXT NOT NULL,
    github_user_id        BIGINT,   -- set after OAuth callback
    github_user_login     TEXT,
    pending_bundle_json   TEXT,   -- TokenBundle awaiting pickup (device flow)
    state                 TEXT NOT NULL DEFAULT 'pending',   -- pending|awaiting_install|awaiting_picker|delivered|cancelled|expired
    created_at            BIGINT NOT NULL,
    expires_at            BIGINT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_auth_sessions_device UNIQUE (device_code),
    CONSTRAINT uq_auth_sessions_user_code UNIQUE (user_code)
);

CREATE INDEX IF NOT EXISTS auth_sessions_expires ON auth_sessions (expires_at);

-- Partial index for efficient expired-lease sweeps (Postgres only).
-- SQLite uses the plain leases_expires index defined above.
CREATE INDEX IF NOT EXISTS leases_expires_partial ON leases (expires_at) WHERE expires_at IS NOT NULL;
