#!/usr/bin/env python3
"""
translate-schema.py — Translate Dolt (MySQL-dialect) DDL to SQLite and Postgres.

Read Dolt's `schema export` output from stdin; write dialect-specific DDL files.

This script is invoked by scripts/gen-schema.sh and by `make schema`.
It is NOT a runtime dependency of the Hub.
"""

import argparse
import re
import sys

HEADER = """\
-- Generated by scripts/gen-schema.sh — DO NOT EDIT BY HAND.
-- Source of truth: db/ (Dolt). Regenerate with `make schema`.\
"""

# Table comments that describe each table — kept identical to the original schema.sql
TABLE_COMMENTS = {
    "deliveries": "-- Deduplication of GitHub webhook deliveries by X-GitHub-Delivery id.",
    "rounds": (
        "-- A Round is the lifecycle of a single PR head SHA (owner/repo#number @ sha).\n"
        "-- A new head SHA is a new Round; see ADR-0004."
    ),
    "pending": (
        "-- Latest-state pending store: at most one row per PR per signal-type, the\n"
        "-- newest summary wins (ADR-0006). Nothing here is garbage-collected; a newer\n"
        "-- same-type event overwrites the row."
    ),
    "signals": (
        "-- Raw signals observed for a Round, compiled into a summary at settle time.\n"
        "-- Keyed by their natural identity so a re-delivered signal replaces, not dupes."
    ),
    "tokens": (
        "-- Hub-minted installation tokens for SSE / get_pending auth (ADR-0003).\n"
        "-- Only the hash is stored; the raw token is shown once at mint time."
    ),
    "installations": "-- GitHub App installations. One row per installation_id.",
    "installation_repos": "-- Repos associated with each installation.",
    "leases": (
        "-- Rebase leases: at most one holder per PR at any time (ADR-0005).\n"
        "-- UNIQUE(org, repo, pr_number) enforces the single-owner invariant.\n"
        "-- All timestamps are Unix epoch seconds (INTEGER) to stay portable to Postgres."
    ),
    "app_credentials": (
        "-- GitHub App credentials persisted after the manifest conversion flow.\n"
        "-- Only one row ever exists (single-app deployment); enforced by CHECK (id = 1)."
    ),
}

# Inline column comments preserved from the original schema
COLUMN_COMMENTS = {
    "signals": {
        "signal_type": "-- checks | comments | mergeability",
        "source":      "-- dynamic attribution, e.g. CI / CodeRabbit",
        "external_id": "-- per-source id for replace/dedupe",
    },
    "tokens": {
        "token_hash": "-- hex sha256 of the raw token",
    },
    "installation_repos": {
        "full_name": '-- "owner/repo"',
    },
    "leases": {
        "holder":            "-- installation_id of current holder",
        "expires_at":        "-- Unix epoch; grant duration set by Hub",
        "last_heartbeat_at": "-- updated by holder; orphan detection uses this",
    },
}

# Desired output order (matches original schema.sql)
TABLE_ORDER = [
    "deliveries",
    "rounds",
    "pending",
    "signals",
    "tokens",
    "installations",
    "installation_repos",
    "leases",
    "app_credentials",
]


def strip_backticks(s: str) -> str:
    return s.replace("`", "")


def parse_tables(raw: str) -> dict[str, list[str]]:
    """
    Parse Dolt schema export into {table_name: [line, ...]}.
    Dolt emits:
        CREATE TABLE `name` (
          line1,
          line2
        ) ENGINE=... ;
    We match by tracking brace depth, not regex over the whole body.
    """
    tables: dict[str, list[str]] = {}
    lines = raw.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        m = re.match(r"CREATE\s+TABLE\s+`?(\w+)`?\s*\(", line, re.IGNORECASE)
        if m:
            tname = m.group(1)
            body_lines: list[str] = []
            depth = line.count("(") - line.count(")")
            i += 1
            while i < len(lines) and depth > 0:
                l = lines[i]
                depth += l.count("(") - l.count(")")
                if depth > 0:
                    body_lines.append(l)
                i += 1
            tables[tname] = body_lines
        else:
            i += 1
    return tables


class TableDef:
    def __init__(self, name: str, columns: list, constraints: list, indexes: list):
        self.name = name
        self.columns = columns          # list of (col_name, raw_def_after_name)
        self.constraints = constraints  # list of (kind, value)
        self.indexes = indexes          # list of (index_name, cols_expr)


def parse_body(table_name: str, body_lines: list[str]) -> TableDef:
    """
    Parse the interior lines of a CREATE TABLE block.
    Returns columns, table-level constraints, and inline indexes.
    """
    columns = []
    constraints = []
    indexes = []

    for raw_line in body_lines:
        line = raw_line.strip().rstrip(",")
        if not line:
            continue

        # PRIMARY KEY (cols)
        if re.match(r"PRIMARY\s+KEY\s*\(", line, re.IGNORECASE):
            val = strip_backticks(line)
            # Normalise comma spacing: (a,b,c) -> (a, b, c)
            val = re.sub(r",\s*", ", ", val)
            constraints.append(("PRIMARY KEY", val))
        # UNIQUE KEY name (cols)
        elif re.match(r"UNIQUE\s+KEY\s+", line, re.IGNORECASE):
            m = re.match(r"UNIQUE\s+KEY\s+`?(\w+)`?\s*\((.+)\)", line, re.IGNORECASE)
            if m:
                ucols = re.sub(r",\s*", ", ", strip_backticks(m.group(2)))
                constraints.append(("UNIQUE", (m.group(1), ucols)))
        # KEY name (cols)  — non-unique index
        elif re.match(r"KEY\s+`?\w+`?\s*\(", line, re.IGNORECASE):
            m = re.match(r"KEY\s+`?(\w+)`?\s*\((.+)\)", line, re.IGNORECASE)
            if m:
                indexes.append((m.group(1), strip_backticks(m.group(2))))
        # CONSTRAINT name CHECK (...)
        elif re.match(r"CONSTRAINT\s+", line, re.IGNORECASE):
            m = re.match(r"CONSTRAINT\s+`?(\w+)`?\s+CHECK\s*\((.+)\)", line, re.IGNORECASE)
            if m:
                check_expr = strip_backticks(m.group(2))
                # Dolt wraps in extra parens: ((id = 1)) -> id = 1
                check_expr = re.sub(r"^\((.+)\)$", r"\1", check_expr)
                constraints.append(("CHECK", check_expr))
        # Regular column
        else:
            m = re.match(r"`?(\w+)`?\s+(.*)", line)
            if m:
                col_name = m.group(1)
                col_def = strip_backticks(m.group(2))
                columns.append((col_name, col_def))

    return TableDef(table_name, columns, constraints, indexes)


def sqlite_type(type_str: str) -> str:
    """Map MySQL type token to SQLite affinity."""
    t = type_str.upper()
    if re.match(r"BIGINT\b|INT\b|INTEGER\b", t):
        return "INTEGER"
    if re.match(r"VARCHAR|TEXT\b|CHAR\b", t):
        return "TEXT"
    return type_str


def postgres_type(type_str: str) -> str:
    """
    Map MySQL type token to idiomatic Postgres type.
    Per postgres design reference:
      - varchar(n) → TEXT  (equivalent; avoids arbitrary limits)
      - bigint     → BIGINT
      - int / integer → INTEGER
      - text       → TEXT
    """
    t = type_str.upper()
    if re.match(r"BIGINT\b", t):
        return "BIGINT"
    if re.match(r"\bINT\b|INTEGER\b", t):
        return "INTEGER"
    if re.match(r"VARCHAR|TEXT\b|CHAR\b", t):
        return "TEXT"
    return type_str


def translate_col_def(col_def: str, type_fn) -> str:
    """
    Translate the type in a column definition string.
    col_def is everything after the column name, e.g. 'varchar(255) NOT NULL DEFAULT ''.
    """
    # Match the type token (with optional size) at the start
    m = re.match(
        r"(varchar\(\d+\)|bigint\b|int\b|integer\b|text\b|char\(\d+\))(.*)",
        col_def,
        re.IGNORECASE,
    )
    if m:
        orig_type = m.group(1)
        rest = m.group(2)
        new_type = type_fn(orig_type)
        return f"{new_type}{rest}"
    return col_def


def _render_body(entries: list) -> str:
    """
    Join body entries with commas, placing trailing comments AFTER the comma.

    Each entry is either:
      - a plain string (constraint line or column without comment)
      - a tuple (sql_part, comment_str) where comment must come after the comma

    Output example:
        signal_type         TEXT NOT NULL,  -- checks | comments | mergeability
        source              TEXT NOT NULL,  -- dynamic attribution
        ...
        PRIMARY KEY (...)
    """
    lines = []
    n = len(entries)
    for idx, entry in enumerate(entries):
        is_last = idx == n - 1
        if isinstance(entry, tuple):
            sql_part, comment = entry
            if is_last:
                lines.append(f"{sql_part}   {comment}")
            else:
                lines.append(f"{sql_part},   {comment}")
        else:
            if is_last:
                lines.append(entry)
            else:
                lines.append(f"{entry},")
    return "\n".join(lines)


def format_sqlite_table(tdef: TableDef) -> str:
    """Render a CREATE TABLE statement in SQLite dialect."""
    entries = []
    tname = tdef.name
    col_comments = COLUMN_COMMENTS.get(tname, {})

    for col_name, col_def in tdef.columns:
        translated = translate_col_def(col_def, sqlite_type)
        comment = col_comments.get(col_name, "")
        col_line = f"    {col_name:<20}{translated}"
        if comment:
            entries.append((col_line, comment))
        else:
            entries.append(col_line)

    for kind, val in tdef.constraints:
        if kind == "PRIMARY KEY":
            entries.append(f"    {val}")
        elif kind == "UNIQUE":
            _, ucols = val
            entries.append(f"    UNIQUE ({ucols})")
        elif kind == "CHECK":
            entries.append(f"    CHECK ({val})")

    body = _render_body(entries)
    result = f"CREATE TABLE IF NOT EXISTS {tname} (\n{body}\n);"

    # Separate CREATE INDEX for non-unique indexes
    extra = [
        f"CREATE INDEX IF NOT EXISTS {iname} ON {tname} ({icols});"
        for iname, icols in tdef.indexes
    ]
    if extra:
        result += "\n\n" + "\n".join(extra)
    return result


def format_postgres_table(tdef: TableDef) -> str:
    """Render a CREATE TABLE statement in Postgres dialect."""
    entries = []
    tname = tdef.name
    col_comments = COLUMN_COMMENTS.get(tname, {})

    for col_name, col_def in tdef.columns:
        translated = translate_col_def(col_def, postgres_type)
        comment = col_comments.get(col_name, "")
        col_line = f"    {col_name:<22}{translated}"
        if comment:
            entries.append((col_line, comment))
        else:
            entries.append(col_line)

    for kind, val in tdef.constraints:
        if kind == "PRIMARY KEY":
            entries.append(f"    {val}")
        elif kind == "UNIQUE":
            uname, ucols = val
            # Idiomatic Postgres: named UNIQUE constraint
            entries.append(f"    CONSTRAINT {uname} UNIQUE ({ucols})")
        elif kind == "CHECK":
            entries.append(f"    CHECK ({val})")

    body = _render_body(entries)
    result = f"CREATE TABLE IF NOT EXISTS {tname} (\n{body}\n);"

    # Non-unique indexes become CREATE INDEX IF NOT EXISTS
    extra = [
        f"CREATE INDEX IF NOT EXISTS {iname} ON {tname} ({icols});"
        for iname, icols in tdef.indexes
    ]
    if extra:
        result += "\n\n" + "\n".join(extra)
    return result


def main():
    parser = argparse.ArgumentParser(description="Translate Dolt DDL to SQLite and Postgres")
    parser.add_argument("--sqlite", required=True, help="Output SQLite DDL file")
    parser.add_argument("--postgres", required=True, help="Output Postgres DDL file")
    args = parser.parse_args()

    raw = sys.stdin.read()
    tables = parse_tables(raw)

    # Determine render order: TABLE_ORDER first, then any extras alphabetically
    ordered = [t for t in TABLE_ORDER if t in tables]
    ordered += sorted(t for t in tables if t not in TABLE_ORDER)

    sqlite_parts = [HEADER, ""]
    postgres_parts = [HEADER, ""]

    for tname in ordered:
        body_lines = tables[tname]
        tdef = parse_body(tname, body_lines)
        comment = TABLE_COMMENTS.get(tname, "")

        # SQLite
        if comment:
            sqlite_parts.append(comment)
        sqlite_parts.append(format_sqlite_table(tdef))
        sqlite_parts.append("")

        # Postgres
        if comment:
            postgres_parts.append(comment)
        postgres_parts.append(format_postgres_table(tdef))
        postgres_parts.append("")

    # Postgres-only partial index for lease expiry sweeps
    postgres_parts.extend([
        "-- Partial index for efficient expired-lease sweeps (Postgres only).",
        "-- SQLite uses the plain leases_expires index defined above.",
        "CREATE INDEX IF NOT EXISTS leases_expires_partial",
        "    ON leases (expires_at)",
        "    WHERE expires_at IS NOT NULL;",
        "",
    ])

    with open(args.sqlite, "w") as f:
        f.write("\n".join(sqlite_parts))

    with open(args.postgres, "w") as f:
        f.write("\n".join(postgres_parts))


if __name__ == "__main__":
    main()
